### ISSUE TITLE
/initial_proposals can not be viewed 

### ISSUE THREAD

**Issue by SnallQiu** [f3rm/f3rm#10]
Hi, thanks for releasing this excellent work! 
I'm enjoying your demo, but find that /initial_proposals can not be viewed, and there is no error in the terminal.
![image](https://github.com/f3rm/f3rm/assets/33489953/70b17a43-f0da-42ce-aaea-ff25219f9130)
![image](https://github.com/f3rm/f3rm/assets/33489953/eb5dc017-b44b-473c-89cc-c0e326244cb2)

**Comment by williamshen-nz** [comment]
Hi what version of viser are you using? We found that there was a bug with the scene tree before 0.17.0

```
pip show viser
```

**Comment by SnallQiu** [comment]
Thank you for the quick reply. 
`pip install viser==0.1.7` is ok.
