### ISSUE TITLE
About heatmap

### ISSUE THREAD

**Issue by Gloryseven** [f3rm/f3rm#14]
May I ask how the heatmap is drawn?

**Comment by williamshen-nz** [comment]
Could you please provide more context on which heatmap?

The 2D rendered heatmap is implemented here: https://github.com/f3rm/f3rm/blob/main/f3rm/model.py

**Comment by Gloryseven** [comment]
Thank you for your reply! I also want to ask How should I debug this project? (Because this project code is build on top of nerfstudio and using GUI for language query, so I do not known how to debug it)

**Comment by williamshen-nz** [comment]
It doesn't make a difference for debugging that we use nerfstudio. You can just use your favorite Python debugger.

If you want to make modifications to the nerfstudio code, then you should clone and install it from source. Just make sure you're using the version specified in our [pyproject.toml](https://github.com/f3rm/f3rm/blob/main/pyproject.toml#L24) file.

**Comment by Gloryseven** [comment]
> Could you please provide more context on which heatmap?
> 
> The 2D rendered heatmap is implemented here: https://github.com/f3rm/f3rm/blob/main/f3rm/model.py

Hello! The heatmap I am referring to is Figure 7 in the paper.  Do you draw it with seaborn library or any other tool?

**Comment by williamshen-nz** [comment]
We created the figure by rendering the 2D similarity heatmap with a cropped bounding box of the NeRF. We used our custom viewer, but you should be able to achieve similar effect with the nerfstudio viewer and minimal code changes.
