### ISSUE TITLE
"f3rm-optimize"  runs very slowly

### ISSUE THREAD

**Issue by dajiebi** [f3rm/f3rm#17]
Point cloud sampling visualization is very fast when using the panda datasets (2000-3000it/s), however, the speed becomes very slow when using my own dataset (0.5it/s)

**Comment by dajiebi** [comment]
The problem does not occur when I add the "--visualize False"

**Comment by williamshen-nz** [comment]
The point cloud sampling samples within the bounds of the robot workspace, which was specific for our Panda setup. 

If you are using your own dataset, you can change the bounds of the workspace here: https://github.com/f3rm/f3rm/blob/main/f3rm_robot/args.py#L34-L36

A good first step would be to make the bounds very big so you can see what it actually looks like.

**Comment by dajiebi** [comment]
Thanks for your reply, the problem has been solved！

**Comment by williamshen-nz** [comment]
Glad to hear!
