### ISSUE TITLE
Hash Grid and MLP Head

### ISSUE THREAD

**Issue by MichaelYu781** [f3rm/f3rm#18]
Hi, i am confused about the what is the meaning of MLP Head and Hash Grid. 
Is the MLP Head means using traditional NeRF-like method to get features, while the Hash Grid uses method like InstantNGP?  
I make a test on different feature encoding config, and find that the outcome using single PE is more similar to the outcome mentioned in the paper. However, i can't figure out what is its relationship with Hash Grid ?
<img width="977" alt="freq" src="https://github.com/f3rm/f3rm/assets/78360527/a6951404-1481-4783-8139-b04339428b56">
the above image uses only PE
<img width="979" alt="hash" src="https://github.com/f3rm/f3rm/assets/78360527/5a1f5c31-8278-4608-867a-47c2f0b32c41">
the above image uses only Hash

**Comment by williamshen-nz** [comment]
Hi, what different config are you testing on?

Regarding hash grid and MLP head, you can find more details in Figure 3 of the [Instant-NGP paper](https://nvlabs.github.io/instant-ngp/) and the [tiny-cuda-nn library](https://github.com/NVlabs/tiny-cuda-nn). The hash grid stores feature vectors which are fed into the MLP head to decode them into the distilled features.

We found using PE smooths out the features, which is a desirable property for the tasks we care about.

**Comment by MichaelYu781** [comment]
Thanks for your response. The first image is the result of using the following encoding config:
```
encoding_config = {
    "otype": "Composite",
    "nested": [
        {
            "otype": "Frequency",
            "n_frequencies": pe_n_freq,
            "n_dims_to_encode": 3,
        }
    ],
}
```

The second image is the result of using the following encoding config :
```
encoding_config = {
    "otype": "Composite",
    "nested": [
        {
            "otype": "HashGrid",
            "n_levels": num_levels,
            "n_features_per_level": features_per_level,
            "log2_hashmap_size": log2_hashmap_size,
            "base_resolution": start_res,
            "per_level_scale": growth_factor,
        }
    ],
}
```

we also tried following configs, the result is also similar to the first image:
```
encoding_config = {
    "otype": "Composite",
    "nested": [
        {
            "otype": "Frequency",
            "n_frequencies": pe_n_freq,
            "n_dims_to_encode": 3,
        },
        {
            "otype": "HashGrid",
            "n_levels": num_levels,
            "n_features_per_level": features_per_level,
            "log2_hashmap_size": log2_hashmap_size,
            "base_resolution": start_res,
            "per_level_scale": growth_factor,
        }
    ],
}
```
```
encoding_config = {
    "otype": "Composite",
    "nested": [
        {
            "otype": "HashGrid",
            "n_levels": num_levels,
            "n_features_per_level": features_per_level,
            "log2_hashmap_size": log2_hashmap_size,
            "base_resolution": start_res,
            "per_level_scale": growth_factor,
        }，
        {
            "otype": "Frequency",
            "n_frequencies": pe_n_freq,
            "n_dims_to_encode": 3,
        }
    ],
}
```

**Comment by MichaelYu781** [comment]
i confused whether PE is combined with Hash? As during my test, the output of encoding config(using Hash + PE) is totally the same as that only using PE(including the training speed). It seems like the process of getting features is using PE to encoding xyz and fedding into the MLP head to decode them into the distilled features, which doesn't involves the participant of Hash.

**Comment by williamshen-nz** [comment]
If you are referring to MLP head in the paper (Appendix A.3.1) then that is something different. There, we use the intermediate output of the Nerfacto (called `density_embedding`) as input to a MLP to predict the features. That implementation is not provided in this repo.

I'm not sure what's happening with the encoder configs you mentioned. I think there might be some internal behavior of tiny-cuda-nn that is being hidden (maybe it is ignoring the hash grid in the encoder). That would require more debugging. We found that the positional encoding (frequency) was key for getting smoother features.

**Comment by MichaelYu781** [comment]
Thanks for your reply!
