### ISSUE TITLE
Question about Sequential Training for Nerf and Feature Field

### ISSUE THREAD

**Issue by Dipan-Zhang** [f3rm/f3rm#19]
Hi, thanks for this nice work!

I learn from paper that the nerf and feature field is trained in a sequential way according to the description at the end of appendix A4. And I am trying to reproduce these results and compare the difference.

However, in the published code I didn't find any config file to control this sequential training behavior. And from my understanding, the feature field is trained together with nerf. 

Is this feature(sequential training) not included in the code, or did I miss something?

**Comment by williamshen-nz** [comment]
Hi! We do not provide sequential training in the code as training both the NeRF and feature field in parallel is sufficient. You should be easily able to modify the code if you want to do it sequentially.

**Comment by Dipan-Zhang** [comment]
Hi！ thanks a lot the answering. 

Yeah I tried with training both in parallel and the quality was already satisfying ;)
