### ISSUE TITLE
About Labeling Demonstrations

### ISSUE THREAD

**Issue by dajiebi** [f3rm/f3rm#20]
About the "a web-based 3D viewer based on Three.js that we developed which supports the real-time rendering of NeRFs, point clouds, and meshes. " mentioned in the article, where can I find this Viewer？Is this from an another paper or an open source work?

**Comment by williamshen-nz** [comment]
Hi, the visualization tool was developed into [Vuer](https://docs.vuer.ai/en/latest/). You can check the examples for point clouds, meshes, movables, etc. Vuer has built-in VR support.

**Comment by williamshen-nz** [comment]
Closing this issue. You can see an example of using Vuer for teleop here: https://github.com/OpenTeleVision/TeleVision
