### ISSUE TITLE
Nerf_to_world.json

### ISSUE THREAD

**Issue by TomTomasaabb** [f3rm/f3rm#7]
Hi, is it available to share the method to create `nerf_to_world.json` for self-sampled data?

**Comment by williamshen-nz** [comment]
Hi, the `nerf_to_world.json` calibration is based on your setup. If you already have ground truth transforms in `transforms.json`, then you can use the inverse of the `dataparser_transforms.json` that nerfstudio writes which contains the scale and transformation shifts applied to the poses.

Otherwise, you will need to find the calibration which you can do using traditional calibration methods.

**Comment by williamshen-nz** [comment]
Closing this issue, feel free to reopen if you have are still encountering problems.

**Comment by KamiPan0601** [comment]
Hi, how can I use the `dataparser_transforms.json` to compute the inverse transformation (Is there a formula) ？ And how can I get `nerf_to_world.json` with the existing `transforms.json`？Thank you :)

> Hi, the `nerf_to_world.json` calibration is based on your setup. If you already have ground truth transforms in `transforms.json`, then you can use the inverse of the `dataparser_transforms.json` that nerfstudio writes which contains the scale and transformation shifts applied to the poses.
> 
> Otherwise, you will need to find the calibration which you can do using traditional calibration methods.

**Comment by dajiebi** [comment]
Hello,could you explain the method of obtaining Nerf_to_world.json in more detail?  I have never been able to make my own Nerf_to_world.json, which resulted in incorrect point sampling in the workspace.The current explanation is too difficult for me！

**Comment by williamshen-nz** [comment]
Hi, please open a new issue if you are encountering problems. We have some additional details on how to calibrate here: https://github.com/f3rm/f3rm/issues/15#issuecomment-2067306367

If there are any individual steps you want clarification on there, you can comment on that issue.

**Comment by dajiebi** [comment]
Sorry to bother you. May I ask why there is no scale in nerf_to_world.json?

**Comment by williamshen-nz** [comment]
The scale is embedded in the 4x4 matrix in `nerf_to_world.json`.
