### ISSUE TITLE
Integration of f3rm with NerfBridge

### ISSUE THREAD

**Issue by javieryu** [f3rm/f3rm#9]
Hi, I'm working on a project called NerfBridge which does continuous NeRF training from a ROS image stream. I'm really excited about your work, and am hoping to integrate some of your code into my project to do live f3rm feature field training. I think for maintenance and compatibility reasons I would like to copy a few specific files from your code into my repository. Would that be okay with all of you? Obviously, I'd put references to your repo and paper at the top of the copied files as well as a citation in the README of NerfBridge and any papers that get published and use that code.

https://github.com/javieryu/nerf_bridge

Cheers,
Javier

**Comment by williamshen-nz** [comment]
Hi Javier,

Yes, that's fine. I've seen NerfBridge before, really cool work! Excited to see what can be done with live feature fields.

Will

**Comment by javieryu** [comment]
Great! Will update you when we make progress on this!
